
install:
	git config --global alias.a 'add'
	git config --global alias.amend 'commit --amend'
	git config --global alias.aliases 'config --get-regexp alias'
	git config --global alias.b 'branch'
	git config --global alias.ball 'branch --all'
	git config --global alias.brnach 'branch'
	git config --global alias.c 'commit'
	git config --global alias.co 'checkout'
	git config --global alias.d 'diff'
	git config --global alias.drop 'checkout --'
	git config --global alias.f 'fetch'
	git config --global alias.graph 'log --oneline --graph --decorate'
	git config --global alias.last 'log HEAD~1..HEAD --oneline'
	git config --global alias.lastdiff 'diff HEAD~1 HEAD'
	git config --global alias.list 'log --oneline'
	git config --global alias.mastiff 'log --oneline master..HEAD'
	git config --global alias.new 'checkout -b'
	git config --global alias.remaster '! _current=$(git branch | sed -n -e "s/^\* \(.*\)/\1/p") && git checkout master && git pull && git checkout $_current && git rebase master'
	git config --global alias.rename 'branch -m'
	git config --global alias.s '!clear && ls && git status'
	git config --global alias.stage 'add'
	git config --global alias.unamend 'reset --soft HEAD@{1}'
	git config --global alias.uncommit 'reset HEAD~1 --soft'
	git config --global alias.unstage 'reset'
